/**
 * Pattern Comparison Page
 * 
 * Dedicated page for multi-pattern comparison and analysis using the
 * similarity comparison dashboard and related components.
 */

import { ComparisonDashboard } from '@/components/comparison';
import { Metadata } from 'next';
import Link from 'next/link';
import PageShell from '@/components/layout/PageShell';

export const metadata: Metadata = {
  title: 'Pattern Comparison - Prompt Pattern Dictionary',
  description: 'Compare multiple prompt patterns using semantic similarity analysis to discover relationships and patterns.',
};

export default function ComparisonPage() {
  return (
    <PageShell variant="wide" noContainer>
      {/* Header */}
      <div className="surface-card border-b rounded-none">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-primary">
                Pattern Comparison
              </h1>
              <p className="mt-2 text-lg text-secondary">
                Analyze similarities between prompt patterns using semantic embeddings
              </p>
            </div>
            <div className="flex items-center space-x-4">
              <Link
                href="/"
                className="text-accent hover:underline font-medium"
              >
                ← Back to Dictionary
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <ComparisonDashboard />
      </div>

      {/* Footer Info */}
      <div className="mt-16 surface-card border-t rounded-none">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center text-secondary">
            <h3 className="text-lg font-medium text-primary mb-4">
              About Pattern Comparison
            </h3>
            <p className="max-w-3xl mx-auto text-sm leading-relaxed">
              This tool uses semantic embeddings generated by Azure OpenAI&apos;s text-embedding-3-large model 
              to calculate similarity scores between prompt patterns. Higher scores indicate patterns that 
              share similar purposes, structures, or semantic content, helping researchers discover 
              relationships and validate their prompt engineering approaches.
            </p>
          </div>
        </div>
      </div>
    </PageShell>
  );
}
